### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Tanitlab/Smarketyrs#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on 'account' when generating the url
const url = 'https://storage.googleapis.com/smarketyrs_js/smarketyrsjs_'+account+'.min.js?ignoreCache=1';

**Comment by Smarketyrs** [comment]
Thank you for the feedback, we have updated our template accordingly.

**Comment by praveena-pappu** [comment]
1) Can you please provide label and placeholder/RegExp for the input field. This helps user to understand the input field details.
![Screenshot 2021-03-23 1 31 41 PM](https://user-images.githubusercontent.com/53495700/112214259-38fb6e80-8bdc-11eb-996f-c19f65c7b277.png)
